language: java
script: mvn clean verify -f resources/fr.univnantes.alma.releng/pom.xml
jdk: oraclejdk8

deploy:
  provider: releases
  api_key: ""
  file: 
	  - $TRAVIS_BUILD_DIR/nBourdin/GitLearning/fr.univnantes.alma.repository/target/products/ALMAServer-linux.gtk.x86_64.zip
	  - $TRAVIS_BUILD_DIR/nBourdin/GitLearning/fr.univnantes.alma.repository/target/products/ALMAServer-win32.win32.x86_64.zip
	  - $TRAVIS_BUILD_DIR/nBourdin/GitLearning/fr.univnantes.alma.repository/target/products/ALMAServer-macosx.cocoa.x86_64.zip
  skip_cleanup: true
  on:
    tags: true
