language: java
script: mvn clean verify -f resources/fr.univnantes.alma.releng/pom.xml
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
   secure: jVJqCELsr7VJN+zvDf+DOxy2mmMPMBF5zisePJkrjP1kJfsOIQRuDvybkoULFuyKT/vou807ENHfWjjY0ZsIYhBb4/BEa2nuSFp/6KxfL0K674UslZBpPD4zt373udeuKfwFkruWk/DgFSngcVzifXKHFmN0aM/deR9N8/tXBrSht60VMJFqUzAqcQTchsQXaIgUCBJmxrcdy2gWMP7Wrc57GGyrBm6ICikklNDo+OPVuSML29WjzInUaMdd0GxDjWiZbl7qeiCIHo+syd+plqBh0YkZuezHXqmz6c4LrOOrpQrx+sWojcIYNl+rfMpliJvoHwHW+RNX4yOK7RAU3A3jLQESfM//qC4ySmr/FxFx6WhVTaBIaRGX+58rT8OMWBTl/TQfJgA15fLRp9kQqaif68VRNSsDEK7cmB5ktm9GFOpzpWhLjo29Y6OJRyo6dkBTM/i1UQBpaoesIwkNzKK/Qmm9AtnUpXsnZsY+WBRuI5ypCij/RPWNrJ3eEQZIZuQ096bGbeFDyHyGhMdacBkz0JfAA+PVNHv8iTQuOXuOH/hJnxmMbseLKysRruAPk8Cd6IVUiYmHgEJDxysyVp44wlhxK9mdXhMdguCkteIMwBOsqvD6vMd5vBRDXsHE38C6/dieLNRELPjaXFJO7AUmKVJLmkVMLjKmxODGf7I=
  file:
  - "$TRAVIS_BUILD_DIR/resources/fr.univnantes.alma.repository/target/products/ALMAServer-win32.win32.x86_64.zip"
  - "$TRAVIS_BUILD_DIR/resources/fr.univnantes.alma.repository/target/products/ALMAServer-linux.gtk.x86_64.zip"
  - "$TRAVIS_BUILD_DIR/resources/fr.univnantes.alma.repository/target/products/ALMAServer-macosx.cocoa.x86_64.zip"
  skip_cleanup: true
  on:
    tags: true
    repo: nBourdin/GitLearning
  password:
    