language: java
script: mvn clean verify -f resources/fr.univnantes.alma.releng/pom.xml
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: yTjtBsDRyHVeVHNLIvTAgOm6HafTlKCozVQLhdNu3d3/A6B53KFMNVogitPeFy9NOXhQmB4rMlHf/RORhDyCg3QgABwB/0Q2KPeRHjpUbxUAlkLUcnRq6Gi8RAN+j1KgeN0UKIz85hPWr8pKA8GT0lNA0q1LfrcrKQosh3E3D2JT3obP7Zpbvmcu4H2c5TUdlKptXJmuQ4Vhg859Gke2fsPhovdx5eddpJiW7mehLIamwJlrLiBOe1+CQemlN38lVWVu9G2A/jPFd6tuH95D/KQv2SXSZt40J4oA3WtXt/qqlD/KtBBr6MiUsCnPed74gsWpUFD+ifjio6qmuIy5mOg+1KAKGulra6ebPkRXaVVl1ezpH9PLwyyw3Mpc1RYp4Cd/nfKmeNmKR1PPzNaV8jrj24MExJ4nAOAyvLKKtVZhFDG/pMEDspgVvH4leMmytJcbo7++k+D3HcBdz73zc4VlLRSvpNfc/SyviHH8fW3zdUatkunbwNiNJKGLcm/RYXzotZGzarWt4mppvXlWluuOrk9OVWC6NyHkBfhVkguhJfJqN2TQTm+sm9x6UY0eUnfi2/ien/Ptr1/nVngBnQyCsNyr2BzjIOTDpZGGzVV+mH3fy1sUlRvtRICCulm6UMeUxMjr2GrJ8+F3pcAT8Qgej2mAbQ0qgN9hZnMT7Mk=
  file_glob: true
  file: resources/fr.univnantes.alma.repository/target/products/ALMAServer-*.zip
  on:
    tags: true
    repo: masters-info-nantes/GitLearning
